package ch11;

/**
 * @author Xu Zheng
 * @description
 */
public class Two_RandomCrashes {
    //what errors could it be? how to test each one?

    //it depends on the type of applications, but some general causes are:

    //1. Random variables or random input. Random variables causes the program to crash in random places.
    //it may be random input from user or a random number generated by the code or based on the current time.

    //2. Uninitialized variables. Some languages give uninitialized variables a random value.

    //3. Memory Leak. The program may run out of memory at some random point depending on the number of processes
    //in the system.

    //4. External Dependencies. The program may depend on other applications, machine or resources. If there are
    //multiple places in the code depending on external resources, the crash could be any place.

    //How to test?
    //1. learn about the application. What does it do? Who is it working with?
    //2. Try to find some patterns. Those crashes may be all relevant to File I/O operations, or database operations.
    //3. Track by elimination. Shut down other processes to see if it is a memory problem. Run it on another machine.
    //Or use a different data source or use other tools to analyse the runtime situation.
    //Check one problem at a time
}
